### ISSUE TITLE
Feature Request: Keyboard Shortcut for Playing Source Audio in Translator Extension

### ISSUE THREAD

**Issue by kse-kot** [caiqichang/vscode-translation#13]
Hello,

I am a frequent user of your Translator extension in Visual Studio Code and appreciate the utility it brings to my workflow. I have a feature request that I believe would enhance the functionality of the extension significantly.

Feature Request:
I would like to propose the addition of a keyboard shortcut that enables users to play the source audio of the text being translated, specifically in the 'complete translation mode'. This feature would be particularly useful for understanding pronunciation and intonation in different languages.

Possible Implementation:
- Command Name: `playSourceAudio`
- Suggested Keyboard Shortcut: `Ctrl + Alt + P` (or any other combination that does not conflict with common VS Code shortcuts)
- Functionality: When a user has translated a piece of text and wishes to hear the audio of the original (source) language, they can use this shortcut to trigger the audio playback.

Thank you for considering this request. Your work on this extension is greatly valued in the developer community.

Best regards,
Kseniia

**Comment by caiqichang** [comment]
Unfortunately, playing sounds is based on chromium webview and it can not work without any user interaction.
See: https://developer.chrome.com/blog/autoplay/
