### ISSUE TITLE
request: supports APIs other than Google

### ISSUE THREAD

**Issue by zjtv** [caiqichang/vscode-translation#14]
I tried multiple vscode plugins and finally found the suitable one. Thanks, but due to being in China and well-known reasons, please support other translation APIs besides Google, such as Azure

**Comment by caiqichang** [comment]
Microsoft Translation API is avaliable now. (after version 3.0.8) 
using these configuration to enable:
```json
{
  // Specifies the translation api provider. (Google or Microsoft)
  "translation.translation-api-provider": "Google",

  // Specifies the voice api provider. (Google or Microsoft)
  "translation.voice-api-provider": "Google"
}
```

**Comment by izturn** [comment]
thx

**Comment by zjtv** [comment]
thx
