### ISSUE TITLE
feature request: default selection

### ISSUE THREAD

**Issue by zjtv** [caiqichang/vscode-translation#15]
Currently, it is necessary to manually double-click a word and then press `alt+x` to translate it.
 If possible, please add the default selection of the word where the cursor is located. 
If do this, we can save one double-click operation and improve translation efficiency.
thx

**Comment by zjtv** [comment]
@caiqichang  Thanks for your quick response, I read your latest pr, maybe I didn't make myself clear, what I suggested is not to hover directly out of the translation result, because in other translation plugins, they will also provide hover function, and then in the position of the cursor to show the translation result, it will be with vscode in other plugins that also need to utilize the hover function, such as the full signature of the function, comments, or whatever put together, makes people feel a bit confused (this is also the reason why I don't choose them), what I suggested is to only when I click alt+x, and then pick up the result. What put together, let a person feel a little confusing (which is why I do not choose them), I suggest is only when I click alt + x, and then pick up the current cursor content as an input parameter then  translate it

**Comment by caiqichang** [comment]
@zjtv 
I have change this function, see the README. The translation only shown when hovering on the selected text, and the translation target is the selected text. 
Due to vscode's api it is impossible to trigger hover popup by any key, or change the content of popup after it is shown.
And you can disable the auto translation via configuration `translation.auto-translate-hovering`, if this done, the hover popup only show translate buttons.

**Comment by zjtv** [comment]
sorry, perhaps I still haven't made it clear.

The function I need is not related to `hover`.

before:
>
    double click  + AltX = result

after:
>
    single/double click  + AltX = result

I don't know if it can be implemented.

thx

**Comment by zjtv** [comment]
btw, At least when it comes to golang, the experience with `hover` is quite poor. 

For example, when translating a `struct` name, if you don't scroll the scrollbar, you won't be able to see it at all as follows: 

![图片](https://github.com/caiqichang/vscode-translation/assets/165639285/74cc556a-91ca-4bef-91e7-8f672da7250e)
